### ISSUE TITLE
Error: has no method 'addCustomPrefix'

### ISSUE THREAD

**Issue by mtclmn** [TelescopeJS/Zeiss#2]
Hi Sacha,

Cool stuff...

I'm trying to do a clean install of Telescope with Zeiss, but I'm getting `TypeError: Object #<Object> has no method 'addCustomPrefix'` on startup.

I'm running the `devel` branch of Telescope, but not sure what the error is from.

**Comment by SachaG** [comment]
Are you 100% sure you're on the devel branch? That error usually comes from running Telescope on `master`.

**Comment by milezzz** [comment]
I've done a few installs now without an issue.  I'd recommend removing your project and starting again.  Here's what I did:

Clone the devel branch of Telescope:

`git clone -b devel https://github.com/TelescopeJS/Telescope.git`

Remove the hubble theme:

`meteor remove telescope:theme-hubble`

Install Zeiss:

`meteor add telescope:zeiss`

**Comment by mtclmn** [comment]
Ah, well, that must have been the case. Followed @milezteg steps and it is now working. Thanks both.

**Comment by SachaG** [comment]
Great! @milezteg thanks for your help!
